version: '3.8'

services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    command: sh -c "pytest -v --tb=short tests/ && uvicorn app.main:app --host 0.0.0.0 --port 8000"
