version: '3.8'

services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"

  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
